[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
hello-clockwork = { path = "../programs/hello_clockwork", features = ["no-entrypoint"], version = "0.1.0" }
clockwork-crank = "1.0.5"
anchor-lang = "0.25.0"
solana-client-helpers = "1.1.0"
solana-sdk = "1.10.29"

[features]
devnet = []