[features]
seeds = false
skip-lint = false

[programs.localnet]
payments = "Da42fsoWLyui6iwABCXNhu8R9JdqLQ9jXvCtCfrmouw9"

[programs.devnet]
payments = "Da42fsoWLyui6iwABCXNhu8R9JdqLQ9jXvCtCfrmouw9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/eliasmoreno/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
