[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-lang = "0.25.0"
anchor-spl = { version = "0.25.0", features = ["dex"] }
clockwork-crank = "1.0.5"
distributor = { path = "../programs/distributor", features = ["no-entrypoint"], version = "0.1.0" }
solana-client-helpers = "1.1.0"
solana-sdk = "1.10.29"

[features]
devnet = []