[features]
seeds = false

[programs.devnet]
hello_clockwork = "HknGoyMfjnHLej2A7naPgeGfTfmUC3K6XZHrwB18u16y"

[programs.localnet]
hello_clockwork = "HknGoyMfjnHLej2A7naPgeGfTfmUC3K6XZHrwB18u16y"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
