[features]
seeds = false

[programs.devnet]
token_transfer = "12tW8jpxqAbKgbcRa4uCKtCUcvpzfr7YpJy9zTVosVWK"

[programs.localnet]
token_transfer = "12tW8jpxqAbKgbcRa4uCKtCUcvpzfr7YpJy9zTVosVWK"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
