[package]
name = "client-payments-program"
version = "0.1.0"
edition = "2021"

[dependencies]
payments-program = { path = "../programs/payments", features = ["no-entrypoint"], version = "0.1.0" }
clockwork-sdk = { path = "../../../clockwork/sdk", version = "1.0.6", features = ["client"] }
anchor-spl = "0.25.0"
anchor-lang = "0.25.0"
solana-sdk = "1.10.29"
solana-client = "1.10.29"

[features]
devnet = []